import type { Metadata } from "next";
import "./globals.css";
import Providers from "./components/Providers";
import localFont from "next/font/local";
import Header from "./components/header";
import Footer from "./components/footer";
import "./fonts/fontawesome/css/solid.css";
import "./fonts/fontawesome/css/fontawesome.css";
import "./fonts/fontawesome/css/brands.css";
import { Suspense } from "react";
import Loading from "./loading";

const myFont = localFont({
  src: "/fonts/IRANSans/IRANSansWeb\(FaNum\).woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${myFont.className} bg-gray-50 text-right`}>
        <Providers>
          <Header />
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
